### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by SReub** [phha/vitowifi_esphome#4]
Hi!

I'm having compiling errors with the provided YAML file. I did all the adaptations to fit my needs (network, ...) but there is a compile error with the needed VitoWifi. My main question is how to properly add your custom component? I'm guessing this is the main reason error. Could you please have a look based on the info below? Any help would be very much appreciated!

My setup:
- HA with ESPhome installed on a RPI
- ESP32 nodeMCU + heater using P300 optolink protocol
- Confirmed working setup with ESP + DIY optolink using the VitoWifi directly compiled with arduino code.

ESPhome core Yaml code:

```
substitutions:
  device_name: ketel
  friendly_name: ketel
  device_description: "Ketel - optolink communicatie"

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  includes:
    - custom_components/optolink
  libraries:
    # use the git version of a library used by a component
    - VitoWifi=https://github.com/bertmelis/VitoWiFi.git

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino
```

For the custom component I manualy copied your git repo to the main folder of ESPhome containing the Yaml files for each node, not sure if this is correct? VitoWifi seems to be installing ok with the provided git repo link

<img width="834" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/38141799/184555190-ae42f948-6562-4c17-aefb-cf634ae9557a.png">

Compile error on VitoWifi library.
￼
<img width="801" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/38141799/184555221-840575db-c2c0-42cd-abd7-30101eb7251c.png">
